spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: mseureka
      password: Senha2024

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
